#!/usr/bin/env python3

import math
import argparse


def new_point(x, y, angle):

    theta = math.pi * (angle/180.0)

    x_ = (x * math.cos(theta)) - (y * math.sin(theta))
    y_ = (x * math.sin(theta)) + (y * math.cos(theta))

    return (x_, y_)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-x', type=int, required=True, help='starting x value')
    parser.add_argument('-y', type=int, required=True, help='starting y value')
    parser.add_argument('-a', '--angle', type=int,
                        required=True, help='angle in degrees')

    args = parser.parse_args()

    (x, y) = new_point(args.x, args.y, args.angle)

    print("R{0} ({1:0.2f}, {2:0.2f}) => ({3:0.2f}, {4:0.2f})".format(
        args.angle,
        args.x, args.y,
        x, y))
